name: build docker image and push aliyun

on: push # 触发事件

jobs:
  build-bin:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2 # THIS IS IMPORTANT
        with:
          python-version: '3.10'
      
      - run: ls
      - run: apk update 
      
      - run: python3 --version
      
      - run: pip --version
      - run: pip install -r requirements.txt
      - run: pip install pyinstaller
      - run: pyinstaller main.py
      - run: ls
