name: build docker image and push aliyun

on: push # 触发事件

jobs:
  build-bin:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - run: su
      - run: uname -a
      - run: apk update 
      - run: apk add python3
      - run: python --version
      - run: apk add py3-pip
      - run: pip --version
      - run: pip install pyinstaller
      - run: pip install -r requirements.txt
      - run: pyinstaller main.py
      - run: ls
