name: build docker image and push aliyun

on: push # 触发事件

jobs:
  build-bin:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - run: apk update 
      - run: apk add python3
      - run: python --version
      - run: apd add py3-pip
      - run: pip --version
