name: build docker image and push aliyun

on: [] # 触发事件

jobs:
  build-bin:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - run: apk update & apk add python3 py3-pip & python --version & pip --version
  
