name: test

on: [push] # 触发事件

jobs:
  build-bin:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - run: apk update & apk add python3 & python --version & py3-pip & pip --version
  
